[build]
builder = "dockerfile"
dockerfilePath = "pgbouncer/Dockerfile"
watchPatterns = ["pgbouncer/**"]

[deploy]
restartPolicyType = "always"
multiRegionConfig = { "us-east4-eqdc4a" = { numReplicas = 3 } }
